<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Emgu.CV" Version="4.13.0.5924" />
      <PackageReference Include="Emgu.CV.Bitmap" Version="4.13.0.5924" />
      <PackageReference Include="Emgu.CV.runtime.windows" Version="4.13.0.5924" />
    </ItemGroup>

    <ItemGroup>
      <Content Update="yolov4-tiny-customBW.cfg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Update="yolov4-tiny-customBW_best.weights">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="yolov4-tiny-customBW.cfg" />
      <Content Include="yolov4-tiny-customBW.cfg">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="yolov4-tiny-customBW_best.weights" />
      <Content Include="yolov4-tiny-customBW_best.weights">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="labels.names" />
      <Content Include="labels.names">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
